/* soapH.h
   Generated by gSOAP 2.8.10 from ims.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#endif

#ifndef SOAP_TYPE_ims__haveFriends
#define SOAP_TYPE_ims__haveFriends (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__haveFriends(struct soap*, struct ims__haveFriends *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__haveFriends(struct soap*, const struct ims__haveFriends *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__haveFriends(struct soap*, const char*, int, const struct ims__haveFriends *, const char*);
SOAP_FMAC3 struct ims__haveFriends * SOAP_FMAC4 soap_in_ims__haveFriends(struct soap*, const char*, struct ims__haveFriends *, const char*);

#ifndef soap_write_ims__haveFriends
#define soap_write_ims__haveFriends(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__haveFriends(soap, data), 0) || soap_put_ims__haveFriends(soap, data, "ims:haveFriends", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__haveFriends(struct soap*, const struct ims__haveFriends *, const char*, const char*);

#ifndef soap_read_ims__haveFriends
#define soap_read_ims__haveFriends(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__haveFriends(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__haveFriends * SOAP_FMAC4 soap_get_ims__haveFriends(struct soap*, struct ims__haveFriends *, const char*, const char*);

#ifndef SOAP_TYPE_ims__haveFriendsResponse
#define SOAP_TYPE_ims__haveFriendsResponse (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__haveFriendsResponse(struct soap*, struct ims__haveFriendsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__haveFriendsResponse(struct soap*, const struct ims__haveFriendsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__haveFriendsResponse(struct soap*, const char*, int, const struct ims__haveFriendsResponse *, const char*);
SOAP_FMAC3 struct ims__haveFriendsResponse * SOAP_FMAC4 soap_in_ims__haveFriendsResponse(struct soap*, const char*, struct ims__haveFriendsResponse *, const char*);

#ifndef soap_write_ims__haveFriendsResponse
#define soap_write_ims__haveFriendsResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__haveFriendsResponse(soap, data), 0) || soap_put_ims__haveFriendsResponse(soap, data, "ims:haveFriendsResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__haveFriendsResponse(struct soap*, const struct ims__haveFriendsResponse *, const char*, const char*);

#ifndef soap_read_ims__haveFriendsResponse
#define soap_read_ims__haveFriendsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__haveFriendsResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__haveFriendsResponse * SOAP_FMAC4 soap_get_ims__haveFriendsResponse(struct soap*, struct ims__haveFriendsResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriends
#define SOAP_TYPE_ims__getFriends (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriends(struct soap*, struct ims__getFriends *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriends(struct soap*, const struct ims__getFriends *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriends(struct soap*, const char*, int, const struct ims__getFriends *, const char*);
SOAP_FMAC3 struct ims__getFriends * SOAP_FMAC4 soap_in_ims__getFriends(struct soap*, const char*, struct ims__getFriends *, const char*);

#ifndef soap_write_ims__getFriends
#define soap_write_ims__getFriends(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriends(soap, data), 0) || soap_put_ims__getFriends(soap, data, "ims:getFriends", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriends(struct soap*, const struct ims__getFriends *, const char*, const char*);

#ifndef soap_read_ims__getFriends
#define soap_read_ims__getFriends(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriends(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriends * SOAP_FMAC4 soap_get_ims__getFriends(struct soap*, struct ims__getFriends *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriendsResponse
#define SOAP_TYPE_ims__getFriendsResponse (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriendsResponse(struct soap*, struct ims__getFriendsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriendsResponse(struct soap*, const struct ims__getFriendsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriendsResponse(struct soap*, const char*, int, const struct ims__getFriendsResponse *, const char*);
SOAP_FMAC3 struct ims__getFriendsResponse * SOAP_FMAC4 soap_in_ims__getFriendsResponse(struct soap*, const char*, struct ims__getFriendsResponse *, const char*);

#ifndef soap_write_ims__getFriendsResponse
#define soap_write_ims__getFriendsResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriendsResponse(soap, data), 0) || soap_put_ims__getFriendsResponse(soap, data, "ims:getFriendsResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriendsResponse(struct soap*, const struct ims__getFriendsResponse *, const char*, const char*);

#ifndef soap_read_ims__getFriendsResponse
#define soap_read_ims__getFriendsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriendsResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriendsResponse * SOAP_FMAC4 soap_get_ims__getFriendsResponse(struct soap*, struct ims__getFriendsResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__removeFriend
#define SOAP_TYPE_ims__removeFriend (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__removeFriend(struct soap*, struct ims__removeFriend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__removeFriend(struct soap*, const struct ims__removeFriend *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__removeFriend(struct soap*, const char*, int, const struct ims__removeFriend *, const char*);
SOAP_FMAC3 struct ims__removeFriend * SOAP_FMAC4 soap_in_ims__removeFriend(struct soap*, const char*, struct ims__removeFriend *, const char*);

#ifndef soap_write_ims__removeFriend
#define soap_write_ims__removeFriend(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__removeFriend(soap, data), 0) || soap_put_ims__removeFriend(soap, data, "ims:removeFriend", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__removeFriend(struct soap*, const struct ims__removeFriend *, const char*, const char*);

#ifndef soap_read_ims__removeFriend
#define soap_read_ims__removeFriend(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__removeFriend(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__removeFriend * SOAP_FMAC4 soap_get_ims__removeFriend(struct soap*, struct ims__removeFriend *, const char*, const char*);

#ifndef SOAP_TYPE_ims__removeFriendResponse
#define SOAP_TYPE_ims__removeFriendResponse (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__removeFriendResponse(struct soap*, struct ims__removeFriendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__removeFriendResponse(struct soap*, const struct ims__removeFriendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__removeFriendResponse(struct soap*, const char*, int, const struct ims__removeFriendResponse *, const char*);
SOAP_FMAC3 struct ims__removeFriendResponse * SOAP_FMAC4 soap_in_ims__removeFriendResponse(struct soap*, const char*, struct ims__removeFriendResponse *, const char*);

#ifndef soap_write_ims__removeFriendResponse
#define soap_write_ims__removeFriendResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__removeFriendResponse(soap, data), 0) || soap_put_ims__removeFriendResponse(soap, data, "ims:removeFriendResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__removeFriendResponse(struct soap*, const struct ims__removeFriendResponse *, const char*, const char*);

#ifndef soap_read_ims__removeFriendResponse
#define soap_read_ims__removeFriendResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__removeFriendResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__removeFriendResponse * SOAP_FMAC4 soap_get_ims__removeFriendResponse(struct soap*, struct ims__removeFriendResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__rejectFriendshipRequest
#define SOAP_TYPE_ims__rejectFriendshipRequest (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__rejectFriendshipRequest(struct soap*, struct ims__rejectFriendshipRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__rejectFriendshipRequest(struct soap*, const struct ims__rejectFriendshipRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__rejectFriendshipRequest(struct soap*, const char*, int, const struct ims__rejectFriendshipRequest *, const char*);
SOAP_FMAC3 struct ims__rejectFriendshipRequest * SOAP_FMAC4 soap_in_ims__rejectFriendshipRequest(struct soap*, const char*, struct ims__rejectFriendshipRequest *, const char*);

#ifndef soap_write_ims__rejectFriendshipRequest
#define soap_write_ims__rejectFriendshipRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__rejectFriendshipRequest(soap, data), 0) || soap_put_ims__rejectFriendshipRequest(soap, data, "ims:rejectFriendshipRequest", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__rejectFriendshipRequest(struct soap*, const struct ims__rejectFriendshipRequest *, const char*, const char*);

#ifndef soap_read_ims__rejectFriendshipRequest
#define soap_read_ims__rejectFriendshipRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__rejectFriendshipRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__rejectFriendshipRequest * SOAP_FMAC4 soap_get_ims__rejectFriendshipRequest(struct soap*, struct ims__rejectFriendshipRequest *, const char*, const char*);

#ifndef SOAP_TYPE_ims__rejectFriendshipRequestResponse
#define SOAP_TYPE_ims__rejectFriendshipRequestResponse (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__rejectFriendshipRequestResponse(struct soap*, struct ims__rejectFriendshipRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__rejectFriendshipRequestResponse(struct soap*, const struct ims__rejectFriendshipRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__rejectFriendshipRequestResponse(struct soap*, const char*, int, const struct ims__rejectFriendshipRequestResponse *, const char*);
SOAP_FMAC3 struct ims__rejectFriendshipRequestResponse * SOAP_FMAC4 soap_in_ims__rejectFriendshipRequestResponse(struct soap*, const char*, struct ims__rejectFriendshipRequestResponse *, const char*);

#ifndef soap_write_ims__rejectFriendshipRequestResponse
#define soap_write_ims__rejectFriendshipRequestResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__rejectFriendshipRequestResponse(soap, data), 0) || soap_put_ims__rejectFriendshipRequestResponse(soap, data, "ims:rejectFriendshipRequestResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__rejectFriendshipRequestResponse(struct soap*, const struct ims__rejectFriendshipRequestResponse *, const char*, const char*);

#ifndef soap_read_ims__rejectFriendshipRequestResponse
#define soap_read_ims__rejectFriendshipRequestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__rejectFriendshipRequestResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__rejectFriendshipRequestResponse * SOAP_FMAC4 soap_get_ims__rejectFriendshipRequestResponse(struct soap*, struct ims__rejectFriendshipRequestResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__acceptFriendshipRequest
#define SOAP_TYPE_ims__acceptFriendshipRequest (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__acceptFriendshipRequest(struct soap*, struct ims__acceptFriendshipRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__acceptFriendshipRequest(struct soap*, const struct ims__acceptFriendshipRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__acceptFriendshipRequest(struct soap*, const char*, int, const struct ims__acceptFriendshipRequest *, const char*);
SOAP_FMAC3 struct ims__acceptFriendshipRequest * SOAP_FMAC4 soap_in_ims__acceptFriendshipRequest(struct soap*, const char*, struct ims__acceptFriendshipRequest *, const char*);

#ifndef soap_write_ims__acceptFriendshipRequest
#define soap_write_ims__acceptFriendshipRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__acceptFriendshipRequest(soap, data), 0) || soap_put_ims__acceptFriendshipRequest(soap, data, "ims:acceptFriendshipRequest", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__acceptFriendshipRequest(struct soap*, const struct ims__acceptFriendshipRequest *, const char*, const char*);

#ifndef soap_read_ims__acceptFriendshipRequest
#define soap_read_ims__acceptFriendshipRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__acceptFriendshipRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__acceptFriendshipRequest * SOAP_FMAC4 soap_get_ims__acceptFriendshipRequest(struct soap*, struct ims__acceptFriendshipRequest *, const char*, const char*);

#ifndef SOAP_TYPE_ims__acceptFriendshipRequestResponse
#define SOAP_TYPE_ims__acceptFriendshipRequestResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__acceptFriendshipRequestResponse(struct soap*, struct ims__acceptFriendshipRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__acceptFriendshipRequestResponse(struct soap*, const struct ims__acceptFriendshipRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__acceptFriendshipRequestResponse(struct soap*, const char*, int, const struct ims__acceptFriendshipRequestResponse *, const char*);
SOAP_FMAC3 struct ims__acceptFriendshipRequestResponse * SOAP_FMAC4 soap_in_ims__acceptFriendshipRequestResponse(struct soap*, const char*, struct ims__acceptFriendshipRequestResponse *, const char*);

#ifndef soap_write_ims__acceptFriendshipRequestResponse
#define soap_write_ims__acceptFriendshipRequestResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__acceptFriendshipRequestResponse(soap, data), 0) || soap_put_ims__acceptFriendshipRequestResponse(soap, data, "ims:acceptFriendshipRequestResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__acceptFriendshipRequestResponse(struct soap*, const struct ims__acceptFriendshipRequestResponse *, const char*, const char*);

#ifndef soap_read_ims__acceptFriendshipRequestResponse
#define soap_read_ims__acceptFriendshipRequestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__acceptFriendshipRequestResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__acceptFriendshipRequestResponse * SOAP_FMAC4 soap_get_ims__acceptFriendshipRequestResponse(struct soap*, struct ims__acceptFriendshipRequestResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriendshipRequest
#define SOAP_TYPE_ims__getFriendshipRequest (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriendshipRequest(struct soap*, struct ims__getFriendshipRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriendshipRequest(struct soap*, const struct ims__getFriendshipRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriendshipRequest(struct soap*, const char*, int, const struct ims__getFriendshipRequest *, const char*);
SOAP_FMAC3 struct ims__getFriendshipRequest * SOAP_FMAC4 soap_in_ims__getFriendshipRequest(struct soap*, const char*, struct ims__getFriendshipRequest *, const char*);

#ifndef soap_write_ims__getFriendshipRequest
#define soap_write_ims__getFriendshipRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriendshipRequest(soap, data), 0) || soap_put_ims__getFriendshipRequest(soap, data, "ims:getFriendshipRequest", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriendshipRequest(struct soap*, const struct ims__getFriendshipRequest *, const char*, const char*);

#ifndef soap_read_ims__getFriendshipRequest
#define soap_read_ims__getFriendshipRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriendshipRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriendshipRequest * SOAP_FMAC4 soap_get_ims__getFriendshipRequest(struct soap*, struct ims__getFriendshipRequest *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriendshipRequestResponse
#define SOAP_TYPE_ims__getFriendshipRequestResponse (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriendshipRequestResponse(struct soap*, struct ims__getFriendshipRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriendshipRequestResponse(struct soap*, const struct ims__getFriendshipRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriendshipRequestResponse(struct soap*, const char*, int, const struct ims__getFriendshipRequestResponse *, const char*);
SOAP_FMAC3 struct ims__getFriendshipRequestResponse * SOAP_FMAC4 soap_in_ims__getFriendshipRequestResponse(struct soap*, const char*, struct ims__getFriendshipRequestResponse *, const char*);

#ifndef soap_write_ims__getFriendshipRequestResponse
#define soap_write_ims__getFriendshipRequestResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriendshipRequestResponse(soap, data), 0) || soap_put_ims__getFriendshipRequestResponse(soap, data, "ims:getFriendshipRequestResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriendshipRequestResponse(struct soap*, const struct ims__getFriendshipRequestResponse *, const char*, const char*);

#ifndef soap_read_ims__getFriendshipRequestResponse
#define soap_read_ims__getFriendshipRequestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriendshipRequestResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriendshipRequestResponse * SOAP_FMAC4 soap_get_ims__getFriendshipRequestResponse(struct soap*, struct ims__getFriendshipRequestResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__haveFriendshipRequest
#define SOAP_TYPE_ims__haveFriendshipRequest (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__haveFriendshipRequest(struct soap*, struct ims__haveFriendshipRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__haveFriendshipRequest(struct soap*, const struct ims__haveFriendshipRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__haveFriendshipRequest(struct soap*, const char*, int, const struct ims__haveFriendshipRequest *, const char*);
SOAP_FMAC3 struct ims__haveFriendshipRequest * SOAP_FMAC4 soap_in_ims__haveFriendshipRequest(struct soap*, const char*, struct ims__haveFriendshipRequest *, const char*);

#ifndef soap_write_ims__haveFriendshipRequest
#define soap_write_ims__haveFriendshipRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__haveFriendshipRequest(soap, data), 0) || soap_put_ims__haveFriendshipRequest(soap, data, "ims:haveFriendshipRequest", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__haveFriendshipRequest(struct soap*, const struct ims__haveFriendshipRequest *, const char*, const char*);

#ifndef soap_read_ims__haveFriendshipRequest
#define soap_read_ims__haveFriendshipRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__haveFriendshipRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__haveFriendshipRequest * SOAP_FMAC4 soap_get_ims__haveFriendshipRequest(struct soap*, struct ims__haveFriendshipRequest *, const char*, const char*);

#ifndef SOAP_TYPE_ims__haveFriendshipRequestResponse
#define SOAP_TYPE_ims__haveFriendshipRequestResponse (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__haveFriendshipRequestResponse(struct soap*, struct ims__haveFriendshipRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__haveFriendshipRequestResponse(struct soap*, const struct ims__haveFriendshipRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__haveFriendshipRequestResponse(struct soap*, const char*, int, const struct ims__haveFriendshipRequestResponse *, const char*);
SOAP_FMAC3 struct ims__haveFriendshipRequestResponse * SOAP_FMAC4 soap_in_ims__haveFriendshipRequestResponse(struct soap*, const char*, struct ims__haveFriendshipRequestResponse *, const char*);

#ifndef soap_write_ims__haveFriendshipRequestResponse
#define soap_write_ims__haveFriendshipRequestResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__haveFriendshipRequestResponse(soap, data), 0) || soap_put_ims__haveFriendshipRequestResponse(soap, data, "ims:haveFriendshipRequestResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__haveFriendshipRequestResponse(struct soap*, const struct ims__haveFriendshipRequestResponse *, const char*, const char*);

#ifndef soap_read_ims__haveFriendshipRequestResponse
#define soap_read_ims__haveFriendshipRequestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__haveFriendshipRequestResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__haveFriendshipRequestResponse * SOAP_FMAC4 soap_get_ims__haveFriendshipRequestResponse(struct soap*, struct ims__haveFriendshipRequestResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriendshipRequests
#define SOAP_TYPE_ims__getFriendshipRequests (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriendshipRequests(struct soap*, struct ims__getFriendshipRequests *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriendshipRequests(struct soap*, const struct ims__getFriendshipRequests *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriendshipRequests(struct soap*, const char*, int, const struct ims__getFriendshipRequests *, const char*);
SOAP_FMAC3 struct ims__getFriendshipRequests * SOAP_FMAC4 soap_in_ims__getFriendshipRequests(struct soap*, const char*, struct ims__getFriendshipRequests *, const char*);

#ifndef soap_write_ims__getFriendshipRequests
#define soap_write_ims__getFriendshipRequests(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriendshipRequests(soap, data), 0) || soap_put_ims__getFriendshipRequests(soap, data, "ims:getFriendshipRequests", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriendshipRequests(struct soap*, const struct ims__getFriendshipRequests *, const char*, const char*);

#ifndef soap_read_ims__getFriendshipRequests
#define soap_read_ims__getFriendshipRequests(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriendshipRequests(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriendshipRequests * SOAP_FMAC4 soap_get_ims__getFriendshipRequests(struct soap*, struct ims__getFriendshipRequests *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getFriendshipRequestsResponse
#define SOAP_TYPE_ims__getFriendshipRequestsResponse (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getFriendshipRequestsResponse(struct soap*, struct ims__getFriendshipRequestsResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getFriendshipRequestsResponse(struct soap*, const struct ims__getFriendshipRequestsResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getFriendshipRequestsResponse(struct soap*, const char*, int, const struct ims__getFriendshipRequestsResponse *, const char*);
SOAP_FMAC3 struct ims__getFriendshipRequestsResponse * SOAP_FMAC4 soap_in_ims__getFriendshipRequestsResponse(struct soap*, const char*, struct ims__getFriendshipRequestsResponse *, const char*);

#ifndef soap_write_ims__getFriendshipRequestsResponse
#define soap_write_ims__getFriendshipRequestsResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getFriendshipRequestsResponse(soap, data), 0) || soap_put_ims__getFriendshipRequestsResponse(soap, data, "ims:getFriendshipRequestsResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getFriendshipRequestsResponse(struct soap*, const struct ims__getFriendshipRequestsResponse *, const char*, const char*);

#ifndef soap_read_ims__getFriendshipRequestsResponse
#define soap_read_ims__getFriendshipRequestsResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getFriendshipRequestsResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getFriendshipRequestsResponse * SOAP_FMAC4 soap_get_ims__getFriendshipRequestsResponse(struct soap*, struct ims__getFriendshipRequestsResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendFriendshipRequest
#define SOAP_TYPE_ims__sendFriendshipRequest (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendFriendshipRequest(struct soap*, struct ims__sendFriendshipRequest *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendFriendshipRequest(struct soap*, const struct ims__sendFriendshipRequest *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendFriendshipRequest(struct soap*, const char*, int, const struct ims__sendFriendshipRequest *, const char*);
SOAP_FMAC3 struct ims__sendFriendshipRequest * SOAP_FMAC4 soap_in_ims__sendFriendshipRequest(struct soap*, const char*, struct ims__sendFriendshipRequest *, const char*);

#ifndef soap_write_ims__sendFriendshipRequest
#define soap_write_ims__sendFriendshipRequest(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendFriendshipRequest(soap, data), 0) || soap_put_ims__sendFriendshipRequest(soap, data, "ims:sendFriendshipRequest", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendFriendshipRequest(struct soap*, const struct ims__sendFriendshipRequest *, const char*, const char*);

#ifndef soap_read_ims__sendFriendshipRequest
#define soap_read_ims__sendFriendshipRequest(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendFriendshipRequest(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendFriendshipRequest * SOAP_FMAC4 soap_get_ims__sendFriendshipRequest(struct soap*, struct ims__sendFriendshipRequest *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendFriendshipRequestResponse
#define SOAP_TYPE_ims__sendFriendshipRequestResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendFriendshipRequestResponse(struct soap*, struct ims__sendFriendshipRequestResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendFriendshipRequestResponse(struct soap*, const struct ims__sendFriendshipRequestResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendFriendshipRequestResponse(struct soap*, const char*, int, const struct ims__sendFriendshipRequestResponse *, const char*);
SOAP_FMAC3 struct ims__sendFriendshipRequestResponse * SOAP_FMAC4 soap_in_ims__sendFriendshipRequestResponse(struct soap*, const char*, struct ims__sendFriendshipRequestResponse *, const char*);

#ifndef soap_write_ims__sendFriendshipRequestResponse
#define soap_write_ims__sendFriendshipRequestResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendFriendshipRequestResponse(soap, data), 0) || soap_put_ims__sendFriendshipRequestResponse(soap, data, "ims:sendFriendshipRequestResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendFriendshipRequestResponse(struct soap*, const struct ims__sendFriendshipRequestResponse *, const char*, const char*);

#ifndef soap_read_ims__sendFriendshipRequestResponse
#define soap_read_ims__sendFriendshipRequestResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendFriendshipRequestResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendFriendshipRequestResponse * SOAP_FMAC4 soap_get_ims__sendFriendshipRequestResponse(struct soap*, struct ims__sendFriendshipRequestResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addFriend
#define SOAP_TYPE_ims__addFriend (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addFriend(struct soap*, struct ims__addFriend *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addFriend(struct soap*, const struct ims__addFriend *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addFriend(struct soap*, const char*, int, const struct ims__addFriend *, const char*);
SOAP_FMAC3 struct ims__addFriend * SOAP_FMAC4 soap_in_ims__addFriend(struct soap*, const char*, struct ims__addFriend *, const char*);

#ifndef soap_write_ims__addFriend
#define soap_write_ims__addFriend(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addFriend(soap, data), 0) || soap_put_ims__addFriend(soap, data, "ims:addFriend", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addFriend(struct soap*, const struct ims__addFriend *, const char*, const char*);

#ifndef soap_read_ims__addFriend
#define soap_read_ims__addFriend(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addFriend(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addFriend * SOAP_FMAC4 soap_get_ims__addFriend(struct soap*, struct ims__addFriend *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addFriendResponse
#define SOAP_TYPE_ims__addFriendResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addFriendResponse(struct soap*, struct ims__addFriendResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addFriendResponse(struct soap*, const struct ims__addFriendResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addFriendResponse(struct soap*, const char*, int, const struct ims__addFriendResponse *, const char*);
SOAP_FMAC3 struct ims__addFriendResponse * SOAP_FMAC4 soap_in_ims__addFriendResponse(struct soap*, const char*, struct ims__addFriendResponse *, const char*);

#ifndef soap_write_ims__addFriendResponse
#define soap_write_ims__addFriendResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addFriendResponse(soap, data), 0) || soap_put_ims__addFriendResponse(soap, data, "ims:addFriendResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addFriendResponse(struct soap*, const struct ims__addFriendResponse *, const char*, const char*);

#ifndef soap_read_ims__addFriendResponse
#define soap_read_ims__addFriendResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addFriendResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addFriendResponse * SOAP_FMAC4 soap_get_ims__addFriendResponse(struct soap*, struct ims__addFriendResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__userLogout
#define SOAP_TYPE_ims__userLogout (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__userLogout(struct soap*, struct ims__userLogout *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__userLogout(struct soap*, const struct ims__userLogout *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__userLogout(struct soap*, const char*, int, const struct ims__userLogout *, const char*);
SOAP_FMAC3 struct ims__userLogout * SOAP_FMAC4 soap_in_ims__userLogout(struct soap*, const char*, struct ims__userLogout *, const char*);

#ifndef soap_write_ims__userLogout
#define soap_write_ims__userLogout(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__userLogout(soap, data), 0) || soap_put_ims__userLogout(soap, data, "ims:userLogout", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__userLogout(struct soap*, const struct ims__userLogout *, const char*, const char*);

#ifndef soap_read_ims__userLogout
#define soap_read_ims__userLogout(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__userLogout(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__userLogout * SOAP_FMAC4 soap_get_ims__userLogout(struct soap*, struct ims__userLogout *, const char*, const char*);

#ifndef SOAP_TYPE_ims__userLogoutResponse
#define SOAP_TYPE_ims__userLogoutResponse (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__userLogoutResponse(struct soap*, struct ims__userLogoutResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__userLogoutResponse(struct soap*, const struct ims__userLogoutResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__userLogoutResponse(struct soap*, const char*, int, const struct ims__userLogoutResponse *, const char*);
SOAP_FMAC3 struct ims__userLogoutResponse * SOAP_FMAC4 soap_in_ims__userLogoutResponse(struct soap*, const char*, struct ims__userLogoutResponse *, const char*);

#ifndef soap_write_ims__userLogoutResponse
#define soap_write_ims__userLogoutResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__userLogoutResponse(soap, data), 0) || soap_put_ims__userLogoutResponse(soap, data, "ims:userLogoutResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__userLogoutResponse(struct soap*, const struct ims__userLogoutResponse *, const char*, const char*);

#ifndef soap_read_ims__userLogoutResponse
#define soap_read_ims__userLogoutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__userLogoutResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__userLogoutResponse * SOAP_FMAC4 soap_get_ims__userLogoutResponse(struct soap*, struct ims__userLogoutResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__userLogin
#define SOAP_TYPE_ims__userLogin (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__userLogin(struct soap*, struct ims__userLogin *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__userLogin(struct soap*, const struct ims__userLogin *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__userLogin(struct soap*, const char*, int, const struct ims__userLogin *, const char*);
SOAP_FMAC3 struct ims__userLogin * SOAP_FMAC4 soap_in_ims__userLogin(struct soap*, const char*, struct ims__userLogin *, const char*);

#ifndef soap_write_ims__userLogin
#define soap_write_ims__userLogin(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__userLogin(soap, data), 0) || soap_put_ims__userLogin(soap, data, "ims:userLogin", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__userLogin(struct soap*, const struct ims__userLogin *, const char*, const char*);

#ifndef soap_read_ims__userLogin
#define soap_read_ims__userLogin(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__userLogin(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__userLogin * SOAP_FMAC4 soap_get_ims__userLogin(struct soap*, struct ims__userLogin *, const char*, const char*);

#ifndef SOAP_TYPE_ims__userLoginResponse
#define SOAP_TYPE_ims__userLoginResponse (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__userLoginResponse(struct soap*, struct ims__userLoginResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__userLoginResponse(struct soap*, const struct ims__userLoginResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__userLoginResponse(struct soap*, const char*, int, const struct ims__userLoginResponse *, const char*);
SOAP_FMAC3 struct ims__userLoginResponse * SOAP_FMAC4 soap_in_ims__userLoginResponse(struct soap*, const char*, struct ims__userLoginResponse *, const char*);

#ifndef soap_write_ims__userLoginResponse
#define soap_write_ims__userLoginResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__userLoginResponse(soap, data), 0) || soap_put_ims__userLoginResponse(soap, data, "ims:userLoginResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__userLoginResponse(struct soap*, const struct ims__userLoginResponse *, const char*, const char*);

#ifndef soap_read_ims__userLoginResponse
#define soap_read_ims__userLoginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__userLoginResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__userLoginResponse * SOAP_FMAC4 soap_get_ims__userLoginResponse(struct soap*, struct ims__userLoginResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__removeUser
#define SOAP_TYPE_ims__removeUser (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__removeUser(struct soap*, struct ims__removeUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__removeUser(struct soap*, const struct ims__removeUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__removeUser(struct soap*, const char*, int, const struct ims__removeUser *, const char*);
SOAP_FMAC3 struct ims__removeUser * SOAP_FMAC4 soap_in_ims__removeUser(struct soap*, const char*, struct ims__removeUser *, const char*);

#ifndef soap_write_ims__removeUser
#define soap_write_ims__removeUser(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__removeUser(soap, data), 0) || soap_put_ims__removeUser(soap, data, "ims:removeUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__removeUser(struct soap*, const struct ims__removeUser *, const char*, const char*);

#ifndef soap_read_ims__removeUser
#define soap_read_ims__removeUser(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__removeUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__removeUser * SOAP_FMAC4 soap_get_ims__removeUser(struct soap*, struct ims__removeUser *, const char*, const char*);

#ifndef SOAP_TYPE_ims__removeUserResponse
#define SOAP_TYPE_ims__removeUserResponse (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__removeUserResponse(struct soap*, struct ims__removeUserResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__removeUserResponse(struct soap*, const struct ims__removeUserResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__removeUserResponse(struct soap*, const char*, int, const struct ims__removeUserResponse *, const char*);
SOAP_FMAC3 struct ims__removeUserResponse * SOAP_FMAC4 soap_in_ims__removeUserResponse(struct soap*, const char*, struct ims__removeUserResponse *, const char*);

#ifndef soap_write_ims__removeUserResponse
#define soap_write_ims__removeUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__removeUserResponse(soap, data), 0) || soap_put_ims__removeUserResponse(soap, data, "ims:removeUserResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__removeUserResponse(struct soap*, const struct ims__removeUserResponse *, const char*, const char*);

#ifndef soap_read_ims__removeUserResponse
#define soap_read_ims__removeUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__removeUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__removeUserResponse * SOAP_FMAC4 soap_get_ims__removeUserResponse(struct soap*, struct ims__removeUserResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addUser
#define SOAP_TYPE_ims__addUser (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addUser(struct soap*, struct ims__addUser *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addUser(struct soap*, const struct ims__addUser *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addUser(struct soap*, const char*, int, const struct ims__addUser *, const char*);
SOAP_FMAC3 struct ims__addUser * SOAP_FMAC4 soap_in_ims__addUser(struct soap*, const char*, struct ims__addUser *, const char*);

#ifndef soap_write_ims__addUser
#define soap_write_ims__addUser(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addUser(soap, data), 0) || soap_put_ims__addUser(soap, data, "ims:addUser", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addUser(struct soap*, const struct ims__addUser *, const char*, const char*);

#ifndef soap_read_ims__addUser
#define soap_read_ims__addUser(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addUser(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addUser * SOAP_FMAC4 soap_get_ims__addUser(struct soap*, struct ims__addUser *, const char*, const char*);

#ifndef SOAP_TYPE_ims__addUserResponse
#define SOAP_TYPE_ims__addUserResponse (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__addUserResponse(struct soap*, struct ims__addUserResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__addUserResponse(struct soap*, const struct ims__addUserResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__addUserResponse(struct soap*, const char*, int, const struct ims__addUserResponse *, const char*);
SOAP_FMAC3 struct ims__addUserResponse * SOAP_FMAC4 soap_in_ims__addUserResponse(struct soap*, const char*, struct ims__addUserResponse *, const char*);

#ifndef soap_write_ims__addUserResponse
#define soap_write_ims__addUserResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__addUserResponse(soap, data), 0) || soap_put_ims__addUserResponse(soap, data, "ims:addUserResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__addUserResponse(struct soap*, const struct ims__addUserResponse *, const char*, const char*);

#ifndef soap_read_ims__addUserResponse
#define soap_read_ims__addUserResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__addUserResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__addUserResponse * SOAP_FMAC4 soap_get_ims__addUserResponse(struct soap*, struct ims__addUserResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getLastMessage
#define SOAP_TYPE_ims__getLastMessage (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getLastMessage(struct soap*, struct ims__getLastMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getLastMessage(struct soap*, const struct ims__getLastMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getLastMessage(struct soap*, const char*, int, const struct ims__getLastMessage *, const char*);
SOAP_FMAC3 struct ims__getLastMessage * SOAP_FMAC4 soap_in_ims__getLastMessage(struct soap*, const char*, struct ims__getLastMessage *, const char*);

#ifndef soap_write_ims__getLastMessage
#define soap_write_ims__getLastMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getLastMessage(soap, data), 0) || soap_put_ims__getLastMessage(soap, data, "ims:getLastMessage", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getLastMessage(struct soap*, const struct ims__getLastMessage *, const char*, const char*);

#ifndef soap_read_ims__getLastMessage
#define soap_read_ims__getLastMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getLastMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getLastMessage * SOAP_FMAC4 soap_get_ims__getLastMessage(struct soap*, struct ims__getLastMessage *, const char*, const char*);

#ifndef SOAP_TYPE_ims__getLastMessageResponse
#define SOAP_TYPE_ims__getLastMessageResponse (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__getLastMessageResponse(struct soap*, struct ims__getLastMessageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__getLastMessageResponse(struct soap*, const struct ims__getLastMessageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__getLastMessageResponse(struct soap*, const char*, int, const struct ims__getLastMessageResponse *, const char*);
SOAP_FMAC3 struct ims__getLastMessageResponse * SOAP_FMAC4 soap_in_ims__getLastMessageResponse(struct soap*, const char*, struct ims__getLastMessageResponse *, const char*);

#ifndef soap_write_ims__getLastMessageResponse
#define soap_write_ims__getLastMessageResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__getLastMessageResponse(soap, data), 0) || soap_put_ims__getLastMessageResponse(soap, data, "ims:getLastMessageResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__getLastMessageResponse(struct soap*, const struct ims__getLastMessageResponse *, const char*, const char*);

#ifndef soap_read_ims__getLastMessageResponse
#define soap_read_ims__getLastMessageResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__getLastMessageResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__getLastMessageResponse * SOAP_FMAC4 soap_get_ims__getLastMessageResponse(struct soap*, struct ims__getLastMessageResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__receiveMessage
#define SOAP_TYPE_ims__receiveMessage (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__receiveMessage(struct soap*, struct ims__receiveMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__receiveMessage(struct soap*, const struct ims__receiveMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__receiveMessage(struct soap*, const char*, int, const struct ims__receiveMessage *, const char*);
SOAP_FMAC3 struct ims__receiveMessage * SOAP_FMAC4 soap_in_ims__receiveMessage(struct soap*, const char*, struct ims__receiveMessage *, const char*);

#ifndef soap_write_ims__receiveMessage
#define soap_write_ims__receiveMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__receiveMessage(soap, data), 0) || soap_put_ims__receiveMessage(soap, data, "ims:receiveMessage", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__receiveMessage(struct soap*, const struct ims__receiveMessage *, const char*, const char*);

#ifndef soap_read_ims__receiveMessage
#define soap_read_ims__receiveMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__receiveMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__receiveMessage * SOAP_FMAC4 soap_get_ims__receiveMessage(struct soap*, struct ims__receiveMessage *, const char*, const char*);

#ifndef SOAP_TYPE_ims__receiveMessageResponse
#define SOAP_TYPE_ims__receiveMessageResponse (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__receiveMessageResponse(struct soap*, struct ims__receiveMessageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__receiveMessageResponse(struct soap*, const struct ims__receiveMessageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__receiveMessageResponse(struct soap*, const char*, int, const struct ims__receiveMessageResponse *, const char*);
SOAP_FMAC3 struct ims__receiveMessageResponse * SOAP_FMAC4 soap_in_ims__receiveMessageResponse(struct soap*, const char*, struct ims__receiveMessageResponse *, const char*);

#ifndef soap_write_ims__receiveMessageResponse
#define soap_write_ims__receiveMessageResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__receiveMessageResponse(soap, data), 0) || soap_put_ims__receiveMessageResponse(soap, data, "ims:receiveMessageResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__receiveMessageResponse(struct soap*, const struct ims__receiveMessageResponse *, const char*, const char*);

#ifndef soap_read_ims__receiveMessageResponse
#define soap_read_ims__receiveMessageResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__receiveMessageResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__receiveMessageResponse * SOAP_FMAC4 soap_get_ims__receiveMessageResponse(struct soap*, struct ims__receiveMessageResponse *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendMessage
#define SOAP_TYPE_ims__sendMessage (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendMessage(struct soap*, struct ims__sendMessage *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendMessage(struct soap*, const struct ims__sendMessage *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendMessage(struct soap*, const char*, int, const struct ims__sendMessage *, const char*);
SOAP_FMAC3 struct ims__sendMessage * SOAP_FMAC4 soap_in_ims__sendMessage(struct soap*, const char*, struct ims__sendMessage *, const char*);

#ifndef soap_write_ims__sendMessage
#define soap_write_ims__sendMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendMessage(soap, data), 0) || soap_put_ims__sendMessage(soap, data, "ims:sendMessage", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendMessage(struct soap*, const struct ims__sendMessage *, const char*, const char*);

#ifndef soap_read_ims__sendMessage
#define soap_read_ims__sendMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendMessage * SOAP_FMAC4 soap_get_ims__sendMessage(struct soap*, struct ims__sendMessage *, const char*, const char*);

#ifndef SOAP_TYPE_ims__sendMessageResponse
#define SOAP_TYPE_ims__sendMessageResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ims__sendMessageResponse(struct soap*, struct ims__sendMessageResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ims__sendMessageResponse(struct soap*, const struct ims__sendMessageResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ims__sendMessageResponse(struct soap*, const char*, int, const struct ims__sendMessageResponse *, const char*);
SOAP_FMAC3 struct ims__sendMessageResponse * SOAP_FMAC4 soap_in_ims__sendMessageResponse(struct soap*, const char*, struct ims__sendMessageResponse *, const char*);

#ifndef soap_write_ims__sendMessageResponse
#define soap_write_ims__sendMessageResponse(soap, data) ( soap_begin_send(soap) || (soap_serialize_ims__sendMessageResponse(soap, data), 0) || soap_put_ims__sendMessageResponse(soap, data, "ims:sendMessageResponse", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_ims__sendMessageResponse(struct soap*, const struct ims__sendMessageResponse *, const char*, const char*);

#ifndef soap_read_ims__sendMessageResponse
#define soap_read_ims__sendMessageResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ims__sendMessageResponse(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct ims__sendMessageResponse * SOAP_FMAC4 soap_get_ims__sendMessageResponse(struct soap*, struct ims__sendMessageResponse *, const char*, const char*);

#ifndef SOAP_TYPE_String
#define SOAP_TYPE_String (14)
#endif

#define soap_default_String(soap, a) soap_default__Struct_3(soap, a)


#define soap_serialize_String(soap, a) soap_serialize__Struct_3(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_String(struct soap*, const char*, int, const struct _Struct_3 *, const char*);
SOAP_FMAC3 struct _Struct_3 * SOAP_FMAC4 soap_in_String(struct soap*, const char*, struct _Struct_3 *, const char*);

#ifndef soap_write_String
#define soap_write_String(soap, data) ( soap_begin_send(soap) || (soap_serialize_String(soap, data), 0) || soap_put_String(soap, data, "String", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_String(struct soap*, const struct _Struct_3 *, const char*, const char*);

#ifndef soap_read_String
#define soap_read_String(soap, data) ( soap_begin_recv(soap) || !soap_get_String(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_3 * SOAP_FMAC4 soap_get_String(struct soap*, struct _Struct_3 *, const char*, const char*);

#ifndef SOAP_TYPE__Struct_3
#define SOAP_TYPE__Struct_3 (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Struct_3(struct soap*, struct _Struct_3 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__Struct_3(struct soap*, const struct _Struct_3 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Struct_3(struct soap*, const char*, int, const struct _Struct_3 *, const char*);
SOAP_FMAC3 struct _Struct_3 * SOAP_FMAC4 soap_in__Struct_3(struct soap*, const char*, struct _Struct_3 *, const char*);

#ifndef soap_write__Struct_3
#define soap_write__Struct_3(soap, data) ( soap_begin_send(soap) || (soap_serialize__Struct_3(soap, data), 0) || soap_put__Struct_3(soap, data, "Struct-3", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__Struct_3(struct soap*, const struct _Struct_3 *, const char*, const char*);

#ifndef soap_read__Struct_3
#define soap_read__Struct_3(soap, data) ( soap_begin_recv(soap) || !soap_get__Struct_3(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_3 * SOAP_FMAC4 soap_get__Struct_3(struct soap*, struct _Struct_3 *, const char*, const char*);

#ifndef SOAP_TYPE_Char_vector
#define SOAP_TYPE_Char_vector (12)
#endif

#define soap_default_Char_vector(soap, a) soap_default__Struct_2(soap, a)


#define soap_serialize_Char_vector(soap, a) soap_serialize__Struct_2(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_Char_vector(struct soap*, const char*, int, const struct _Struct_2 *, const char*);
SOAP_FMAC3 struct _Struct_2 * SOAP_FMAC4 soap_in_Char_vector(struct soap*, const char*, struct _Struct_2 *, const char*);

#ifndef soap_write_Char_vector
#define soap_write_Char_vector(soap, data) ( soap_begin_send(soap) || (soap_serialize_Char_vector(soap, data), 0) || soap_put_Char_vector(soap, data, "Char-vector", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Char_vector(struct soap*, const struct _Struct_2 *, const char*, const char*);

#ifndef soap_read_Char_vector
#define soap_read_Char_vector(soap, data) ( soap_begin_recv(soap) || !soap_get_Char_vector(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_2 * SOAP_FMAC4 soap_get_Char_vector(struct soap*, struct _Struct_2 *, const char*, const char*);

#ifndef SOAP_TYPE__Struct_2
#define SOAP_TYPE__Struct_2 (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Struct_2(struct soap*, struct _Struct_2 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__Struct_2(struct soap*, const struct _Struct_2 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Struct_2(struct soap*, const char*, int, const struct _Struct_2 *, const char*);
SOAP_FMAC3 struct _Struct_2 * SOAP_FMAC4 soap_in__Struct_2(struct soap*, const char*, struct _Struct_2 *, const char*);

#ifndef soap_write__Struct_2
#define soap_write__Struct_2(soap, data) ( soap_begin_send(soap) || (soap_serialize__Struct_2(soap, data), 0) || soap_put__Struct_2(soap, data, "Struct-2", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__Struct_2(struct soap*, const struct _Struct_2 *, const char*, const char*);

#ifndef soap_read__Struct_2
#define soap_read__Struct_2(soap, data) ( soap_begin_recv(soap) || !soap_get__Struct_2(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_2 * SOAP_FMAC4 soap_get__Struct_2(struct soap*, struct _Struct_2 *, const char*, const char*);

#ifndef SOAP_TYPE_Message
#define SOAP_TYPE_Message (9)
#endif

#define soap_default_Message(soap, a) soap_default__Struct_1(soap, a)


#define soap_serialize_Message(soap, a) soap_serialize__Struct_1(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_Message(struct soap*, const char*, int, const struct _Struct_1 *, const char*);
SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_in_Message(struct soap*, const char*, struct _Struct_1 *, const char*);

#ifndef soap_write_Message
#define soap_write_Message(soap, data) ( soap_begin_send(soap) || (soap_serialize_Message(soap, data), 0) || soap_put_Message(soap, data, "Message", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Message(struct soap*, const struct _Struct_1 *, const char*, const char*);

#ifndef soap_read_Message
#define soap_read_Message(soap, data) ( soap_begin_recv(soap) || !soap_get_Message(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_get_Message(struct soap*, struct _Struct_1 *, const char*, const char*);

#ifndef SOAP_TYPE__Struct_1
#define SOAP_TYPE__Struct_1 (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__Struct_1(struct soap*, struct _Struct_1 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__Struct_1(struct soap*, const struct _Struct_1 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__Struct_1(struct soap*, const char*, int, const struct _Struct_1 *, const char*);
SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_in__Struct_1(struct soap*, const char*, struct _Struct_1 *, const char*);

#ifndef soap_write__Struct_1
#define soap_write__Struct_1(soap, data) ( soap_begin_send(soap) || (soap_serialize__Struct_1(soap, data), 0) || soap_put__Struct_1(soap, data, "Struct-1", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put__Struct_1(struct soap*, const struct _Struct_1 *, const char*, const char*);

#ifndef soap_read__Struct_1
#define soap_read__Struct_1(soap, data) ( soap_begin_recv(soap) || !soap_get__Struct_1(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_1 * SOAP_FMAC4 soap_get__Struct_1(struct soap*, struct _Struct_1 *, const char*, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerToString
#define SOAP_TYPE_PointerToString (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToString(struct soap*, struct _Struct_3 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToString(struct soap*, const char *, int, struct _Struct_3 *const*, const char *);
SOAP_FMAC3 struct _Struct_3 ** SOAP_FMAC4 soap_in_PointerToString(struct soap*, const char*, struct _Struct_3 **, const char*);

#ifndef soap_write_PointerToString
#define soap_write_PointerToString(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToString(soap, data), 0) || soap_put_PointerToString(soap, data, "String", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToString(struct soap*, struct _Struct_3 *const*, const char*, const char*);

#ifndef soap_read_PointerToString
#define soap_read_PointerToString(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToString(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_3 ** SOAP_FMAC4 soap_get_PointerToString(struct soap*, struct _Struct_3 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToChar_vector
#define SOAP_TYPE_PointerToChar_vector (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToChar_vector(struct soap*, struct _Struct_2 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToChar_vector(struct soap*, const char *, int, struct _Struct_2 *const*, const char *);
SOAP_FMAC3 struct _Struct_2 ** SOAP_FMAC4 soap_in_PointerToChar_vector(struct soap*, const char*, struct _Struct_2 **, const char*);

#ifndef soap_write_PointerToChar_vector
#define soap_write_PointerToChar_vector(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToChar_vector(soap, data), 0) || soap_put_PointerToChar_vector(soap, data, "Char-vector", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToChar_vector(struct soap*, struct _Struct_2 *const*, const char*, const char*);

#ifndef soap_read_PointerToChar_vector
#define soap_read_PointerToChar_vector(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToChar_vector(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_2 ** SOAP_FMAC4 soap_get_PointerToChar_vector(struct soap*, struct _Struct_2 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToMessage
#define SOAP_TYPE_PointerToMessage (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToMessage(struct soap*, struct _Struct_1 *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToMessage(struct soap*, const char *, int, struct _Struct_1 *const*, const char *);
SOAP_FMAC3 struct _Struct_1 ** SOAP_FMAC4 soap_in_PointerToMessage(struct soap*, const char*, struct _Struct_1 **, const char*);

#ifndef soap_write_PointerToMessage
#define soap_write_PointerToMessage(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToMessage(soap, data), 0) || soap_put_PointerToMessage(soap, data, "Message", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToMessage(struct soap*, struct _Struct_1 *const*, const char*, const char*);

#ifndef soap_read_PointerToMessage
#define soap_read_PointerToMessage(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToMessage(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 struct _Struct_1 ** SOAP_FMAC4 soap_get_PointerToMessage(struct soap*, struct _Struct_1 **, const char*, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data), 0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif

#define soap_default_xsd__string(soap, a) soap_default_string(soap, a)


#define soap_serialize_xsd__string(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_xsd__string
#define soap_write_xsd__string(soap, data) ( soap_begin_send(soap) || (soap_serialize_xsd__string(soap, data), 0) || soap_put_xsd__string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_xsd__string
#define soap_read_xsd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap) )
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_Array100Ofstring
#define SOAP_TYPE_Array100Ofstring (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array100Ofstring(struct soap*, char *[100]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array100Ofstring(struct soap*, char *const[100]);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array100Ofstring(struct soap*, const char*, int, char *const[100], const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_in_Array100Ofstring(struct soap*, const char*, char *[100], const char*);

#ifndef soap_write_Array100Ofstring
#define soap_write_Array100Ofstring(soap, data) ( soap_begin_send(soap) || (soap_serialize_Array100Ofstring(soap, data), 0) || soap_put_Array100Ofstring(soap, data, "SOAP-ENC:Array", NULL) || soap_end_send(soap) )
#endif


SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array100Ofstring(struct soap*, char *const[100], const char*, const char*);

#ifndef soap_read_Array100Ofstring
#define soap_read_Array100Ofstring(soap, data) ( soap_begin_recv(soap) || !soap_get_Array100Ofstring(soap, data, NULL, NULL) || soap_end_recv(soap) )
#endif

SOAP_FMAC3 char * * SOAP_FMAC4 soap_get_Array100Ofstring(struct soap*, char *[100], const char*, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
